{% set version = "6.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-writexls
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WriteXLS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WriteXLS/WriteXLS_{{ version }}.tar.gz
  sha256: 644b90a82683c668b6e05bb4f940111a42cd634f63a5b559351e8cd4274a19b7

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('WriteXLS')"           # [not win]
    - "\"%R%\" -e \"library('WriteXLS')\""  # [win]

about:
  home: https://github.com/marcschwartz/WriteXLS
  license: GPL-2.0-or-later
  summary: 'Cross-platform Perl based R function to create Excel 2003 (XLS) and Excel 2007 (XLSX) files from one or more data frames. Each data frame will be written to a separate named worksheet in the Excel spreadsheet. The worksheet name will be the name of the data frame it contains or can be specified by the user. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: WriteXLS
# Version: 5.0.0
# Date: 2019-05-24
# Title: Cross-Platform Perl Based R Function to Create Excel 2003 (XLS) and Excel 2007 (XLSX) Files
# Description: Cross-platform Perl based R function to create Excel 2003 (XLS) and Excel 2007 (XLSX) files from one or more data frames. Each data frame will be written to a separate named worksheet in the Excel spreadsheet. The worksheet name will be the name of the data frame it contains or can be specified by the user.
# Author: Marc Schwartz <marc_schwartz@me.com> and various authors for Perl modules listed in each .pm file.
# Copyright: The copyright holders of the Perl files are listed in each .pm file under the Perl directory.
# Maintainer: Marc Schwartz <marc_schwartz@me.com>
# License: GPL (>= 2)
# SystemRequirements: Perl
# Imports: utils
# URL: https://github.com/marcschwartz/WriteXLS
# BugReports: https://github.com/marcschwartz/WriteXLS/issues
# NeedsCompilation: no
# Packaged: 2019-05-24 14:35:14 UTC; marcschwartz
# Repository: CRAN
# Date/Publication: 2019-05-25 22:50:13 UTC
