travis:
  secure:
    BINSTAR_TOKEN: qdKfqwDB0SDxETTB6/TD0AnnugX1lBupLZjJDfMlwnApxrRut+Ouh5CnRnWRCJ77X+z3b8jyjSEXynKU0iLoNe8yknI+wverOVzk6mpENJCFxg/ctJYyC3GR6JJT5xOCQxUt7gP7nLR/GM1rmO2qH9dIGbpYRiO+GtKh1nOuXmEf1+MUrfu0lmK/YPNJeKgo8kLPKokYqtbIzCebG0Ofr5T9QBb3IlO3MNh0vgsr+Pb953TlCTXt5uRa5BsHhSC0ztKw8C1Q5mwNfACKoaSxo7n5safoGlg0VLv0iRKLvrYVXCX0h08DIvIaA2lxiK6GuWlmgQtKxSNxhfx31Ui6T7vS1GbrEx21QIsz2tnCS3fDQanUn2axW3DZ+jESiRgBPsUJdHUqH3JRYcHX1U9jD/frCUDlf6xNEIrWtqlmRofZoFiW+jZ1JcbQesBxLhqfIyFrQievvszHsGzE5nTeW+ksX3xfxS0pTP2HbpD/a715eEjDIh4yur0l7qdhyLWRSJMy9n1boA9B1IpP69zDaa7t07tYYIVlc+6SFZK6eGGSWOEGo00BZIW9Xg0BSF0wMoCoeLHFGkbSjnL1PKNMccU8izJ1srR994zCfNp0z2UXsn1iFlnpt4IP1GLNmQAtYIE5n9xsf6MKl+x1nD11E3m9OTGTvs57d/8z7GgYv/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
