travis:
  secure:
    BINSTAR_TOKEN: a8fKxRtjzfuJBx/YMq72iAYe1NaJLV/8EbHl4WvDhQvrq/3cPWHjlX0mmo4rndvD3IFq9vSOXWzkEzzc72xi9E9xiGnon3Wi/dce2qI2UwABrzriSP4U7ayQytQ+cTq1W4Ca2BC3JZIKFSWzQfCef/jX3U16wjpWbTfSIqG+REq4L2P9Az7O3vto6NghsLdzo8QA1uQTVw78UoQdwTmD54ugHjF7kSXoRxkBtDSp5MYUiJWfSu8uOvZnvkrLHq4dswjHMmqSFv6poHS02/mTLzTZq4r8iO1/KvN08a3hu/qnKGyUEQtK4LgxQyBMWhzQkevBPBCwuBJXtYcbhljKQu1G8vOqvC3O8xdh6J5xBioahF9sXldYCm4Nv8aDCB4rLjj6iY+DdlcYxcExLsFmFjVmaBgDaQ4eQk0FKb7qo3WLyKSG5iK+ukZA3xxltVs3MGB9cpEPqwGVkv8sYBiEYS911D/fa0GIJeL7dYvbPeTapVYMr0bLxbAfeZRlTXOaL3z7LCEOdwpzmPTqVz+G9COkG8Og1wSYmItLGGp5xNLnGvL2tHukvYKj87DbW8M/kGo0uOq2QxybEOsZjrPwKDv5wIQWfmVowiwVU8Cbk2tC23INC/qwnG47Hc7gfejMXF9rsqK02i7tq4kQhQrJyQw+mh68HdCTcGFGVTgThbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
